### ISSUE TITLE
SyntaxError: Attempted to redefine property 'lineJoin'.

### ISSUE THREAD

**Issue by yukku0423** [phi-jp/phina.js#117]
iOS 8.3 Safariにて `SyntaxError: Attempted to redefine property 'lineJoin'.` というエラーがでます。
ソースを見てみたところ、phina.graphics.Canvas にて lineJoin が二つ定義されているのが原因のようです。
実装の内容は同じようなのでどちらか削除するのはどうでしょうか。

https://github.com/phi-jp/phina.js/blob/develop/src/graphics/canvas.js#L710

**Comment by phi-jp** [comment]
@yukku0423 san

なんとー, ご指摘ありがとうございます!
修正しました!!

https://github.com/phi-jp/phina.js/commit/85657915f94f596729b8ee344ec46edd7f5f9eb4

**Comment by yukku0423** [comment]
ありがとうございました。問題のエラーがでなくなりました。
