### ISSUE TITLE
this.super.methodName でスーパクラスメソッドが使えるようにしたい & 'use strict' 対応

### ISSUE THREAD

**Issue by simiraaaa** [phi-jp/phina.js#49]
`this.super` は `this.superMethod` でもいいかとおもってます。
`superMethod('methodName')()` か `superMethod('methodName',引数)`ってやるのは簡単そうですが、
`superMethod.methodName()` だとめんどくさそうです

**Comment by phi-jp** [comment]
@simiraaaa san

`superMethod('methodName',引数)` であっても結構面倒そうだと思うんですが,
どういう想定ですか？？

**Comment by simiraaaa** [comment]
applyすれば良いかと思ってましたが、親クラスでさらにsuperMethod呼んでるとダメでしたね....
これは永遠に実装されないかもしれないw

**Comment by phi-jp** [comment]
@simiraaaa san
そうなんですよw
一筋縄ではいかないんですTT

なので superInit は凄い中身複雑になってて, それと同じやり方でやればできなくはないんですが...
非推奨のプロパティとか参照するので極力使いたくないんですよね.

**Comment by simiraaaa** [comment]
@phi-jp さん
こんな感じでしょうか？
http://goo.gl/ZwPMX7

オレオレライブラリではcallee使いたくなかった('use strict'してて使えなかった)ので
_classTreeを使って呼んだ回数分たどる方式でやってるので、それとほとんど同じやり方でやりました。

ほか言語でもsuperあんまり使わないでの仕様がいまいち分からず
とりあえず、こういう仕様で書きました。
superInit は superMethod('init')と同じ
superMethod('method')が呼ばれると親クラスのmethodを実行する
superMethod内でさらに同じmethod名でsuperMethodが呼ばれると親の親...と再帰的に呼ぶ。
superMethod内で普通のメソッドが呼ばれたときは、親クラスのメソッドではなく自身のメソッド
superMethod('a')内で別名のsuperMethod('b')が呼ばれた場合は、bに関してはaの時点での親クラスではなくbが再帰的に呼ばれた回数分の親クラス(メソッド名が違えば親をたどらない)

**Comment by phi-jp** [comment]
なるほどー, この仕組良いですね♪
_classTree より _hierarchy とかのほうが良いかなぁなんて思いました.

**Comment by simiraaaa** [comment]
そうですね。変数名は適当なので、この仕様でやるときは変数名はお任せします

**Comment by phi-jp** [comment]
@simiraaaa san
use strict; も有効にしたいですし @simiraaaa san の方針で実装したいと思います.
(次のバージョンでw)

**Comment by phi-jp** [comment]
対応する!

**Comment by phi-jp** [comment]
@simiraaaa san
めちゃめちゃ参考になりました!!
ほぼ同じ実装で対応しましたb

**Comment by phi-jp** [comment]
対応 done
https://github.com/phi-jp/phina.js/commit/b0b3138c441822c25691cc3962a452a47f0c2246
https://github.com/phi-jp/phina.js/commit/532d13a7e9098b1a0a8de4aac986992eef63bbac

**Comment by phi-jp** [comment]
@simiraaaa san
ご教授頂いたサンプルで, _superMethod 何度か呼ぶとエラーが出る問題と返り値がない問題を修正しました.

当時このクラス実装作ったときに, caller ないと無理だと思っていたのですが
こういった実装があったんですね!!

勉強になりましたmm

**Comment by phi-jp** [comment]
demo and test
http://goo.gl/vWCKIk

**Comment by simiraaaa** [comment]
参考になってよかったです
自分もライブラリを作ってみようと思って作ってるとき一番苦戦しました。
当時はどうしても'use strict' 使いたくてずっと考えてた甲斐があります(なぜかuse strict 使えるとかっこいいと思ってた笑)

**Comment by phi-jp** [comment]
かっこいいw
分かりますよ♪

ってことで phina.js かっこ良くなりましたb

**Comment by phi-jp** [comment]
問題なければ close しますね♪

**Comment by simiraaaa** [comment]
大丈夫ですcloseします
