### ISSUE TITLE
onflickのようなイベントを定義する

### ISSUE THREAD

**Issue by alkn203** [phi-jp/phina.js#50]
onpointstartとonpointendを使って自分で作れなくもないが、スマホ利用を想定してフリック操作を一発で検知する機能が欲しい。
##### 機能例
- タッチ時間や距離といったしきい値？を設定できるようにする。（クラス化必要？）
- フリックされた方向を取得できるようにする。e.directionのようなイメージ。

**Comment by simiraaaa** [comment]
@alkn203  @phi-jp 
http://goo.gl/R8CTAS
昔、FlickArrowを参考に作ったやつです
しきい値に関しては、lengthSquared() < 2 の　2を thresholdみたいなメンバ変数にすれば良いと思います。

デフォルトではこんな感じのクラスをInteractive側で更新して、flickが判定されたらflickイベントを発火すれば良いと思います。
離した時の判定をなくせばスワイプも判定できると思います。

**Comment by phi-jp** [comment]
@simiraaaa san
やりかたとしてはそうでしょうね♪

@alkn203 san 
これアクセサリーで定義する想定ですかね? それともグローバルな感じ??

位置づけとしては, https://github.com/phi-jp/phina.js/blob/develop/src/accessory/draggable.js に近い感じがするので flickable.js でも作ろうかなと思ってます!!

**Comment by alkn203** [comment]
@phi-jp さん flickableの感じで良いかと思います。
プロパティで色々と動作指定できたら最高っすね♪

**Comment by phi-jp** [comment]
@alkn203 san
お！ じゃそっちの方向で実装してみますね♪

**Comment by alkn203** [comment]
flickableが実装されたのでクローズしますね。
