### ISSUE TITLE
Tweener FPS 対応

### ISSUE THREAD

**Issue by simiraaaa** [phi-jp/phina.js#52]
とりあえず、忘れないようにissue化しました。
以下gitterコピペです

```
 var time = 1000/app.fps; // 通常
var time = app.ticker.deltaTime; // フレームスキップ
var time = 1; // fps
```
この３パターンがあると思ってまして
tweener に引数で type 渡して, それ見て分岐とかですかねぇ

simiraaaa 10月 21 16:47
分岐で_update = _updateTweenByFpsとかですかね？

phi-jp 10月 21 16:47
ですかね
_updateTween と _updateWait どちらも反映させないと行けないので関数切り分けて getUnitTime 的なの作ったほうが良いかも

**Comment by phi-jp** [comment]
あざっす, これサンプルもなかったでしたっけ？

**Comment by simiraaaa** [comment]
getUnitTime切り分けたサンプルはないので、あんまり参考にならないと思って載せてません

**Comment by phi-jp** [comment]
@simiraaaa san 了解です!

**Comment by phi-jp** [comment]
memo

```
var time = 1000/app.fps; // 通常
var time = app.ticker.deltaTime; // フレームスキップ
var time = 1; // fps
```
