### ISSUE TITLE
equals(a, deep) or deepEquals(a)

### ISSUE THREAD

**Issue by phi-jp** [phi-jp/phina.js#54]
Array の メソッドなんですが,

`equals(a, deep)` と `deepEquals(a)`

どっちが良いですかね？

https://github.com/phi-jp/phina.js/blob/develop/src/core/array.js#L45

**Comment by daishihmr** [comment]
これはどちらか片方あればよさげですね。

```equals(a, deep)``` だとコード読む時に第2引数が何を意味するのかphina.jsのソースを当たらないとわからないかもしれないので、 ```deepEquals(a)``` がいいと思います。

**Comment by alkn203** [comment]
意味という点では、equals(a, {deep: true})　ってのも。
見た目ごちゃついてますがw

**Comment by phi-jp** [comment]
今後, deep 以外にもオプションがありそうであれば @alkn203 san の案もありですね.

**Comment by phi-jp** [comment]
一旦 deepEquals ってことで close します.
