### ISSUE TITLE
オブジェクトのworldMatrixからグローバルの座標が簡単に取れるメソッドが欲しい

### ISSUE THREAD

**Issue by alkn203** [phi-jp/phina.js#59]
オブジェクトのworldMatrixからグローバルの座標が簡単に取れれば、当たり判定とかに便利ではないかと思います。
* getGlobalPosition でVector2返す
* getGlobalX
* getGlobalY
みたいな感じで。

**Comment by alkn203** [comment]
提案はしてみましたが、作り込むよりも素直に相対座標で補正した方が手っ取り早そうなので、一旦取り下げますね♪

**Comment by phi-jp** [comment]
おっ了解です!
