### ISSUE TITLE
phina.globalizeがないとphina.game.GameAppが動かない(v0.1.0)

### ISSUE THREAD

**Issue by altkaye** [phi-jp/phina.js#61]
phina.js:10745 Uncaught ReferenceError: ManagerScene is not defined

src/game/gameapp.js line 19

      var scene = ManagerScene({
        startLabel: startLabel,

globalizeを前提としているコードのため、普通にphina.game.GameApp()と呼ぶとエラーで落ちます。

**Comment by altkaye** [comment]
再現コード
http://goo.gl/wJWSKT

**Comment by phi-jp** [comment]
@altkaye san

これって close しちゃって大丈夫ですか？

**Comment by altkaye** [comment]
okです！

**Comment by phi-jp** [comment]
確認ありがとうございます!
close します!!
