### ISSUE TITLE
Shapeで_dirtyDraw = true にするアクセサを定義する用のメソッド

### ISSUE THREAD

**Issue by simiraaaa** [phi-jp/phina.js#74]
http://goo.gl/AIJ6RG

**Comment by simiraaaa** [comment]
まず、static を継承するようにcreateClassを変更する必要があります。

```javascript

phina.define('SomethingShape', {
  superClass: 'phina.display.Shape',
  
  init:function...

...
})
// defineとつなげて使う想定
.shapeAccessors([
'arrowWidth',
'arrowRadius'
]);

// 繋げなくてもあとから
SomethingShape.shapeAccessors([
'skewX',
'skewY'
]);

```

という感じの使い方を想定しています。

**Comment by simiraaaa** [comment]
あと、未定義のShapeのサブクラスを継承する場合にこの使い方ができないので、クラスがロード可能になった時のイベントみたいなものがあると、継承するクラスの読み込み完了時に(既に定義済みの場合は即時)、イベントセットしておけば問題なく動くかと思います。

**Comment by phi-jp** [comment]
```
_defined: function(class) {
  // TODO: 定義完了後の処理
},
```

的な感じっすかね？

**Comment by simiraaaa** [comment]
@phi-jp san そんな感じですね。
_map とかその他の処理をいろいろcreateClassに追加していくと、関数自体が大きくなりすぎて良くない感じがするので、_defined で

```javascript

_defined: function(){
  phina.memberMap(this.prototype, {
  x: 'position.x'
  });

  this.shapeAccessor(['radius']);
}

```

みたいにやると今後createClassの中身を変更しなくても良くなると思います

**Comment by phi-jp** [comment]
@simiraaaa san とりあえず実装しておきましたーb
https://github.com/phi-jp/phina.js/commit/97a31fa79b1b5e303a3ad4d609619fa46e7d7d4e

**Comment by simiraaaa** [comment]
@phi-jp san あざっす
あとstaticの継承もしたいですね

**Comment by phi-jp** [comment]
@simiraaaa san

> あとstaticの継承もしたいですね

あまり必要な場面ってのが思い浮かばないのですが
どんなときに使います？？

**Comment by simiraaaa** [comment]
shapeAccessorsがstatic継承してやってるので...
あと、直感的にstaticって継承しませんか？

**Comment by simiraaaa** [comment]
@phi-jp san STATICは継承しない方向で、こんな感じですかね？
http://goo.gl/2LF6ih

```javascript

  _defined:function(){
    
    Shape.shapeAccessors(this, [
    'lineCap',
    'arrowWidth',
    'arrowRadius']);
    
  },
```

**Comment by phi-jp** [comment]
@simiraaaa san

なんか見たことある実装だなと思ったら, 実は最初は watch という shapeAccessors 的な機能を使って
そんな感じの実装にしてたんですよね.

ただ, この場合だと _dirtyDraw を変更以外に何かしたいとき
例えば

```
      radius: {
        "get": function()   {
          return (this.boundingType === 'rect') ?
            (this.width+this.height)/4 : this._radius;
        },
        "set": function(v)  {
          this._dirtyDraw = true;
          this._radius = v;
          this._diameter = v*2;
        },
      },
```

みたいなときに対応できなくて結局コードがバラけちゃうのでやめちゃったんですよね.
ん〜, とはいえ今のコードがイケてないのは十分承知してます.

どうしたものか...

**Comment by phi-jp** [comment]
コード残ってました.

object.js

```
  if (!Object.observe) {
    Object.method('observe', function(obj, callback) {
      var keys = Object.keys(obj);
      keys.forEach(function(key) {
        var tempKey = '__' + key;
        var tempValue = obj[key];
        obj[tempKey] = tempValue;
        
        obj.accessor(key, {
          get: function() {
            return this[tempKey];
          },
          set: function(v) {
            this[tempKey] = v;
            callback();
          },
        });
      });
    });
  }
```

**Comment by phi-jp** [comment]
@simiraaaa san

`getOwnPropertyDescriptor ` とかいう超絶便利なメソッドを見つけました!!
ちょっとこれ使ってやってみます!!

**Comment by phi-jp** [comment]
@simiraaaa san 
めっちゃ複雑になっちゃいましたが, なんとなく実装できました！
レビューしてもらえると幸いです.

https://github.com/phi-jp/phina.js/tree/feature/shape_refactor

**Comment by simiraaaa** [comment]
```javascript
+  Object.prototype.method('$watch', function(key, callback) {
+    var target = this;
+    var descriptor = null;
+
+    while(target) {
+      descriptor = Object.getOwnPropertyDescriptor(target, key);
+      if (descriptor) {
+        break;
+      }
+      target = target.__proto__;
+    }
+
```

target = thisはなにか理由がありますか？

**Comment by phi-jp** [comment]
@simiraaaa san
直後のループで使っています.

アクセッサが定義されているのが継承元だった場合の対応です.

**Comment by simiraaaa** [comment]
あ、よく見たらそうでしたw
`target = target.__proto__;`
`target = Object.getPrototypeOf(target);`
の方がよさそうです

**Comment by phi-jp** [comment]
@simiraaaa san

あざっす, 修正しましたー.
アクセッサだった場合の考慮に苦労しましたorz

`getOwnPropertyDescriptor` 便利すぎです!

**Comment by simiraaaa** [comment]
watchDrawと_dirtyDrawは分けたのって理由あります？

**Comment by simiraaaa** [comment]
あ、watchDraw はtrueにしておくと変更に関係なくマイフレーム描画って感じでしょうか？

**Comment by phi-jp** [comment]
@simiraaaa san

`watchDraw` は完全に止めるやつですね.
`_dirtyDraw` 内部で再描画するかどうかの判定に使うために使うという感じです.

tmlib.js 時代の Shape っぽく使いたい場合に` watchDraw = false;` するイメージです.

テストのこの辺を見てもらえればわかるかと思います.
https://github.com/phi-jp/phina.js/compare/develop...feature/shape_refactor#diff-a50eeba8173edc9a1a7c220c61f59507R38

**Comment by simiraaaa** [comment]
watchDraw &&を||と見間違えてました、なるほどです

**Comment by simiraaaa** [comment]
```javascript
watchRenderProperty: function(key) {
         this.prototype.$watch(key, function() {
           this._dirtyDraw = true;
...

```

これなんですが、staticを継承しないことを想定すると

```javascript
watchRenderProperty: function(self, key) {
         self.prototype.$watch(key, function() {
           this._dirtyDraw = true;
...

```

で使うときは
`phina.display.Shape.watchRenderProperty(this, 'width')`
のような感じが良いですね

**Comment by simiraaaa** [comment]
あと、これは好みだと思いますが

```javascript
this.watchRenderProperty('width');
+      this.watchRenderProperty('height');
+      this.watchRenderProperty('radius');
+      this.watchRenderProperty('padding');
+      this.watchRenderProperty('backgroundColor');
+      this.watchRenderProperty('fill');
+      this.watchRenderProperty('stroke');
+      this.watchRenderProperty('strokeWidth');
+      this.watchRenderProperty('shadow');
+      this.watchRenderProperty('shadowBlur');

```

```javascript

[
'width',
'height',
,,,,
].forEach(function(key){
  phina.display.Shape.watchRenderProperty(this, key);
},this);
```

の方が個人的には好きですが、見た目が良くないので、
いっそのこと`watchRenderPropertys`を定義しておいて配列で定義できると良いかもしれません。

**Comment by phi-jp** [comment]
@simiraaaa san

さすが把握はやいですねw

> phina.display.Shape.watchRenderProperty(this, 'width')

確かに! 修正します!

**Comment by phi-jp** [comment]
まさにいまその修正をしようと思ってました!

**Comment by simiraaaa** [comment]
:+1:

**Comment by phi-jp** [comment]
@simiraaaa san

each の修正は入れました.
ただ, 

> phina.display.Shape.watchRenderProperty(this, 'width')

に関しては, まだこの時点(_defined実行時) は, まだ phina.display.Shape が定義されてないんですよね;;
https://github.com/phi-jp/phina.js/commit/2f84ebd3342ff0e8d56295483bfce07e2eaacc33

**Comment by simiraaaa** [comment]
phina.defineで定義したクラスの定義タイミングってどのタイミングですか？
文字列で継承とかがいろいろあってタイミング把握できてないです

**Comment by simiraaaa** [comment]
```javascript
set: function(v) {
          this[accesskey] = v;
          callback.call(this);
        },

```
$watchの
こことほかの部分のsetもなんですが、
現在の値と全く同じ値だったかどうかわかるといいかなぁと思いました。
無駄に
_dirtyDraw = true にしたくないってだけなんですが、同じ値じゃない場合は無駄な処理が増えるだけなんですよね。

```
var b = this[accesskey] === v;
this[accesskey] = v;
callback.call(this,temp);


watchRenderProperty: function(b){
this._dirtyDraw = !b;
}
```

これは、今までもチェックしてなかったので、なくても大丈夫だとは思います。
無駄が少なくなるならやっておいてもいいかなぁって感じです。

**Comment by simiraaaa** [comment]
```

width: {
-        get: function() {
-          return (this.boundingType === 'rect') ?
-            this._width : this._diameter;
-        },
-        set: function(v) {
-          this._dirtyDraw = true; this._width = v;
-        },
-      },
-      height: {
-        get: function() {
-          return (this.boundingType === 'rect') ?
-            this._height : this._diameter;
-        },
-        set: function(v) {
-          this._dirtyDraw = true; this._height = v;
-        },
-      },
-      radius: {
-        "get": function()   {
-          return (this.boundingType === 'rect') ?
-            (this.width+this.height)/4 : this._radius;
-        },
-        "set": function(v)  {
-          this._dirtyDraw = true;
-          this._radius = v;
-          this._diameter = v*2;
-        },
-      },
```
このへんの削除は一旦これであとからもとの使用に戻したりしますか？

**Comment by phi-jp** [comment]
外でてるんで戻ったらちゃんと返信します！
早いレビューすごく助かります！

**Comment by phi-jp** [comment]
@simiraaaa san
> このへんの削除は一旦これであとからもとの使用に戻したりしますか？

今のやつを採用すれば以前のやつは消すつもりです.
戻したいかんじですか？

**Comment by phi-jp** [comment]
@simiraaaa san

watch で呼ばれる関数の引数に新しい値と古い値を渡すようにしましたb
https://github.com/phi-jp/phina.js/commit/8c2d8a7873e6b24314ca3742c4f585cb88581a9a

**Comment by alkn203** [comment]
@phi-jp さん　細かいところまではさすがに分かりませんが、leftやtopなどこれまで独自に定義してたアクセッサへの影響が気になるところです。的外れだったらすみません。

**Comment by phi-jp** [comment]
@alkn203 san

レビューありがとうございますmm

Shape で `_dirtyDraw = true` にしてたアクセッサのみ変更するだけです.
left や top などへの影響はないですよ♪

**Comment by alkn203** [comment]
オッケーです♪

**Comment by simiraaaa** [comment]
@phi-jp san
戻したいというわけではないんですが、まだ、最初に言ってた問題が解決できてないので、それが対応できたら戻すかと思いました。

>ただ, この場合だと _dirtyDraw を変更以外に何かしたいとき
>例えば

      radius: {
        "get": function()   {
          return (this.boundingType === 'rect') ?
            (this.width+this.height)/4 : this._radius;
        },
        "set": function(v)  {
          this._dirtyDraw = true;
          this._radius = v;
          this._diameter = v*2;
        },
      },
>みたいなときに対応できなくて結局コードがバラけちゃうのでやめちゃったんですよね.
ん〜, とはいえ今のコードがイケてないのは十分承知してます.

>どうしたものか...

**Comment by phi-jp** [comment]
@simiraaaa san

あれ? 今の実装だと解決できている認識です...

**Comment by simiraaaa** [comment]
@phi-jp san
どんな感じでやるのかイメージできてないです...
上のradiusみたいな単純に値を変更する以外の処理をしたいときは、どういうふうに書くんですか？

**Comment by phi-jp** [comment]
@simiraaaa san

言いたいこと理解しました.
その場合も単純に $watch してもらって大丈夫ですよb

Shape の width や radius を削除したのは, 継承元と同じ実装をしちゃってたからです.
今回, 削除したものに関しては Object2d で実装してあるので影響はないです.

**Comment by phi-jp** [comment]
@simiraaaa san

問題なければマージしちゃおうと思ってるんですがどうでしょう？

**Comment by phi-jp** [comment]
確認済みとのことなのでマージします♪
