### ISSUE TITLE
Physicalクラスのforceメソッドの引数を増減量指定方式にする

### ISSUE THREAD

**Issue by alkn203** [phi-jp/phina.js#75]
現在のforceメソッドは結局のところ

```
velocity.set(x,y)
```
と同じなので、「force = 力を加える」 と解釈すると

```
force: function(x, y) {
      this.velocity.x += x;
      this.velocity.y += y;
},
```

とした方が、メソッド名にも合った処理になるのではないかと思います。

**Comment by phi-jp** [comment]
@alkn203 san

確かにそうですね!
変更しますかね？

ただ今の force は, それはそれでよく使うと思うので
なんか別の名前で残したいですね.

set じゃちょっと味気ないし... ん〜

**Comment by alkn203** [comment]
今の force はそのままにして、増減版を addForce にするとか？

**Comment by phi-jp** [comment]
@alkn203 san そうします!!

**Comment by phi-jp** [comment]
なんか良い名前思いついたらぜひ!

**Comment by alkn203** [comment]
了解です！
ここまでの件、pull req しましょうか？

**Comment by phi-jp** [comment]
@alkn203 さん

pull req してくれると嬉しいです :smile

**Comment by alkn203** [comment]
オッケーです👌

**Comment by phi-jp** [comment]
@alkn203 san マージしました.
気がむたら close しといてもらえると幸いです.

**Comment by alkn203** [comment]
Thanks!
