### ISSUE TITLE
SpriteのsrcRectを後から設定した時にSpriteのサイズも合わせるようにする

### ISSUE THREAD

**Issue by alkn203** [phi-jp/phina.js#91]
画像の一部分を切り抜いてSpriteに設定する時に便利です。
よろしければ、pull req させて頂きます。

srcRectをphina.geom.Rectで設定

```
this.srcRect = phina.geom.Rect(0, 0, this.width, this.height);
```

以下でsrcRectが変更可能、Spriteのサイズもリサイズする

```
setSourceRect: function(x, y, width, height) {
  this.srcRect.set(x, y, width, height);
  this.setSize(width, height);
},
```

以下、サンプルです。
http://goo.gl/I3j8te

**Comment by phi-jp** [comment]
@alkn203 san
レス遅くなってすみませんmm

ちょっとこの辺 frameIndex との兼ね合いがあるので, 難しいんですよね💦
一旦現状のままでもこんな感じでやれるんですが, ダメですかね？
http://goo.gl/5hQ1tc

**Comment by phi-jp** [comment]
@alkn203 san

あと地味に実装ちょっと変えました.
setImage が追加されてて, @alkn203 san のアドバイス頂いたように srcRect を Rect クラスに変更しました!
https://github.com/phi-jp/phina.js/commit/cf7efea1a323ee9f11a18a5dd2e2e365d93451a2

**Comment by alkn203** [comment]
@phi-jp さん　コメントありがとうございます。
確かに領域指定は、setFrameIndexに任せた方が良いですね。使い方勉強になりました♪
setImageも後から画像差し替えられるので便利ですね。とても良いと思います♪

**Comment by phi-jp** [comment]
@alkn203 san
良かったです:D

15パズル楽しみにしてます♪w

**Comment by alkn203** [comment]
リツイートありがとうございます！
自分も楽しみながら、phina.jsらしく書ければと思っています♪

このissueはクローズしますね。
