### ISSUE TITLE
スプライト用画像の背景色に透過処理を行える機能の追加

### ISSUE THREAD

**Issue by alkn203** [phi-jp/phina.js#93]
ネット上で公開されている背景色入りの素材などを、ライブラリ側で透過処理して使用できるようになれば便利だと思います。

仕様案
* 画像の1番左上のピクセル、もしくは指定した色を透過する
* アセット読み込み時、もしくはSpriteクラスのコンストラクタ内で処理

課題
* クロスドメインでの画像扱い制約にどう対処するか

**Comment by alkn203** [comment]
ベタな方法ですがそれらしい処理ができたので、参考までにコード載せます。（Windows + Chromeで動作確認済み）
http://goo.gl/a8y2pp

クロスオリジンの問題は別にして、やはり、どのタイミングで処理を行うかがカギになりそうですね。
* imageとは別にアセットの種類を1つ増やして、Textureクラスのコンストラクタに引数を渡して処理
* スプライト生成時だと、シューティングゲームのように頻繁にスプライト作る場合に速度的に影響？

**Comment by phi-jp** [comment]
素晴らしい, じっくり見させていただきます!!

**Comment by phi-jp** [comment]
メソッドを生やすだけのデモ

http://goo.gl/8mGUsI

**Comment by daishihmr** [comment]
透過色の指定が出来ても便利かも。
無指定だったら左上隅のピクセルってことで。

**Comment by phi-jp** [comment]
確かに!
その方針で対応しますb

**Comment by alkn203** [comment]
言い出しっぺなので、書いてみました。
http://goo.gl/hp2x8E

**Comment by alkn203** [comment]
一旦マージされたのでクローズします。

**Comment by phi-jp** [comment]
:smile:
