### ISSUE TITLE
phina.geom.Vector2.fromAngleの実装とコメントが一致していない

### ISSUE THREAD

**Issue by techno-cat** [phi-jp/phina.js#96]
Branch: develop
コメントではdegreeを期待しているが、実装はradianを想定している。

今の実装であれば（Numberの拡張にならって）、
toAngle / fromAngleをtoRadian / fromRadianに置き換えるか、
置き換えた上でtoDegree / fromDegreeを追加しても良いと思うのですが、
いかがでしょうか？

**Comment by phi-jp** [comment]
@techno-cat san
確かに...
修正しますね!

**Comment by phi-jp** [comment]
@techno-cat san
こんな感じでどうでしょう？
https://github.com/phi-jp/phina.js/commit/c5f1a96a68de2cb28f28e7120b60c6d7382e3e96

**Comment by techno-cat** [comment]
@phi-jp san

冷静になって考えてみたら、
コメントだけ修正すれば良んですよね、気付きませんでした。
お騒がせしました。

**Comment by phi-jp** [comment]
これ close しちゃっても大丈夫ですか？

**Comment by techno-cat** [comment]
https://github.com/phi-jp/phina.js/commit/c5f1a96a68de2cb28f28e7120b60c6d7382e3e96 については、コミットにコメントした通りです。
こちらはcloseしても大丈夫です、対応ありがとうございました！

**Comment by phi-jp** [comment]
len 対応しましたb
クローズしますね♪
